sheet_names:
  empresas: "EMPRESAS"
  licencas: "LICENÇAS"
  taxas: "TAXAS"
  processos: "PROCESSOS"   # ÚNICA ABA de Processos
  uteis: "CONTATOS E MODELOS"

# Nomes das Tabelas (ListObjects) dentro da aba PROCESSOS
# — estas strings devem bater exatamente com os nomes dos ListObjects no Excel
table_names:
  processos:
    diversos: "Diversos"
    funcionamento: "Funcionamento"
    bombeiros: "Bombeiros"
    uso_solo: "UsoDoSolo"
    sanitario: "Sanitario"
    ambiental: "Ambiental"

  uteis:
    contatos: "Contatos"
    modelos: "Modelos"

column_aliases:

  empresas:
    ID: ["ID"]
    EMPRESA: ["EMPRESA", "RAZÃO SOCIAL", "RAZAO SOCIAL"]
    CNPJ: ["CNPJ"]
    PORTE: ["PORTE"]
    MUNICIPIO: ["MUNICÍPIO", "MUNICIPIO", "CIDADE"]
    CATEGORIA: ["CATEGORIA", "ATIVIDADE", "RAMO"]
    IE: ["IE", "INSCRIÇÃO ESTADUAL", "INSCRICAO ESTADUAL"]
    IM: ["IM", "INSCRIÇÃO MUNICIPAL", "INSCRICAO MUNICIPAL"]
    SITUACAO: ["SITUAÇÃO", "SITUACAO", "STATUS"]
    DEBITO_PREFEITURA: ["DÉBITO PREFEITURA", "DEBITO PREFEITURA", "DÉBITOS PREFEITURA", "DEBITOS PREFEITURA"]
    CERTIFICADO_DIGITAL: ["CERTIFICADO DIGITAL", "CERTIFICADO", "CERT DIGITAL"]
    OBS: ["OBS", "OBSERVAÇÃO", "OBSERVACOES", "OBSERVAÇÕES"]
    PROPRIETARIO_PRINCIPAL: ["PROPRIETÁRIO PRINCIPAL", "PROPRIETARIO PRINCIPAL", "SÓCIO PRINCIPAL", "SOCIO PRINCIPAL"]
    CPF: ["CPF", "CPF PROPRIETÁRIO", "CPF PROPRIETARIO"]
    TELEFONE: ["TELEFONE", "FONE", "CELULAR", "WHATSAPP"]
    E_MAIL: ["E-MAIL", "EMAIL", "E MAIL"]
    RESPONSAVEL_FISCAL: ["RESPONSÁVEL FISCAL", "RESPONSAVEL FISCAL", "CONTADOR RESPONSÁVEL", "CONTADOR RESPONSAVEL"]

  licencas:
    ID: ["ID"]
    EMPRESA: ["EMPRESA", "RAZÃO SOCIAL", "RAZAO SOCIAL"]
    CNPJ: ["CNPJ"]
    MUNICIPIO: ["MUNICÍPIO", "MUNICIPIO", "CIDADE"]

    SANITARIA_STATUS: ["ALVARÁ VIG SANITÁRIA", "ALVARA VIG SANITARIA", "ALVARÁ SANITÁRIO", "ALVARA SANITARIO", "SANITÁRIA", "SANITARIA"]
    SANITARIA_VAL: ["VALIDADE SANITÁRIA", "VALIDADE SANITARIA", "VAL SANITÁRIA", "VAL SANITARIA", "VEN SANITÁRIA", "VEN SANITARIA"]

    FUNCIONAMENTO_STATUS: ["ALVARÁ FUNCIONAMENTO", "ALVARA FUNCIONAMENTO", "FUNCIONAMENTO", "ALVARÁ DE FUNCIONAMENTO"]
    FUNCIONAMENTO_VAL: ["VALIDADE FUNCIONAMENTO", "VAL FUNCIONAMENTO", "VEN FUNCIONAMENTO"]

    AMBIENTAL_STATUS: ["LICENÇA AMBIENTAL", "LICENCA AMBIENTAL", "AMBIENTAL"]
    AMBIENTAL_VAL: ["VALIDADE AMBIENTAL", "VAL AMBIENTAL", "VEN AMBIENTAL"]

    USO_SOLO_STATUS: ["CERTIDÃO USO DO SOLO", "CERTIDAO USO DO SOLO", "USO DO SOLO", "CERT. USO DO SOLO", "C.U.SOLO"]
    USO_SOLO_VAL: ["VALIDADE USO DO SOLO", "VAL USO DO SOLO", "VEN USO DO SOLO"]

    CERCON_STATUS: ["CERCON", "CERTIFICADO REGULARIDADE CONTRA INCÊNDIO", "CERTIFICADO REGULARIDADE CONTRA INCENDIO", "CERTIFICADO BOMBEIROS", "CERT. BOMBEIROS", "CBMGO"]
    CERCON_VAL: ["VALIDADE CERCON", "VAL CERCON", "VALIDADE BOMBEIROS", "VAL BOMBEIROS", "VEN CERCON", "VEN BOMBEIROS"]

    OBS: ["OBS", "OBSERVAÇÃO", "OBSERVACOES", "OBSERVAÇÕES"]

  taxas:
    ID: ["ID"]
    EMPRESA: ["EMPRESA", "RAZÃO SOCIAL", "RAZAO SOCIAL"]
    CNPJ: ["CNPJ"]
    MUNICIPIO: ["MUNICÍPIO", "MUNICIPIO", "CIDADE"]

    TPI: ["TPI", "SICABOM (TPI)", "TAXA POTENCIAL INCÊNDIO", "TAXA POTENCIAL INCENDIO", "TAXA DOS BOMBEIROS", "BOMBEIROS (TPI)"]
    FUNCIONAMENTO: ["FUNCIONAMENTO", "TAXA DE FUNCIONAMENTO", "ALVARÁ FUNCIONAMENTO", "ALVARA FUNCIONAMENTO"]
    PUBLICIDADE: ["PUBLICIDADE", "TAXA DE PUBLICIDADE", "TAXA PUBLICIDADE", "ANÚNCIO", "ANUNCIO"]
    SANITARIA: ["SANITÁRIA", "SANITARIA", "VIGILÂNCIA SANITÁRIA", "VIGILANCIA SANITARIA", "VISA"]
    OBS: ["OBS", "OBSERVAÇÃO", "OBSERVACOES", "OBSERVAÇÕES"]

  # Aliases de colunas para cada Tabela (ListObject) dentro de PROCESSOS.
  # Colunas COMUNS a todos os tipos de processo
  processos_diversos:
    ID: ["ID"]
    EMPRESA: ["EMPRESA", "RAZÃO SOCIAL", "RAZAO SOCIAL"]
    CNPJ: ["CNPJ"]
    MUNICIPIO: ["MUNICÍPIO", "MUNICIPIO", "CIDADE"]
    PROTOCOLO: ["PROTOCOLO", "Nº PROTOCOLO", "NUMERO PROTOCOLO", "N PROTOCOLO"]
    TIPO: ["TIPO", "TIPO DE PROCESSO", "CLASSE", "DIVERSOS"]
    ASSUNTO: ["ASSUNTO", "DESCRIÇÃO", "DESCRICAO"]
    ORGAO: ["ÓRGÃO", "ORGAO", "SECRETARIA"]
    DATA_SOLICITACAO: ["DATA SOLICITAÇÃO", "DATA SOLICITACAO", "SOLICITAÇÃO", "SOLICITACAO", "ABERTURA", "DATA ABERTURA"]
    SITUACAO: ["SITUAÇÃO", "SITUACAO", "STATUS"]
    PRAZO: ["PRAZO", "DATA LIMITE", "DEADLINE"]
    OBS: ["OBS", "OBSERVAÇÃO", "OBSERVACOES", "OBSERVAÇÕES"]
    # Campos específicos de Diversos
    OPERACAO: ["OPERAÇÃO", "OPERACAO", "TIPO OPERAÇÃO", "TIPO OPERACAO"]

  processos_funcionamento:
    ID: ["ID"]
    EMPRESA: ["EMPRESA", "RAZÃO SOCIAL", "RAZAO SOCIAL"]
    CNPJ: ["CNPJ"]
    PROTOCOLO: ["PROTOCOLO", "Nº PROTOCOLO", "NUMERO PROTOCOLO"]
    DATA_SOLICITACAO: ["DATA SOLICITAÇÃO", "DATA SOLICITACAO", "SOLICITAÇÃO", "SOLICITACAO"]
    SITUACAO: ["SITUAÇÃO", "SITUACAO", "STATUS"]
    PRAZO: ["PRAZO", "DATA LIMITE"]
    OBS: ["OBS", "OBSERVAÇÃO", "OBSERVACOES"]
    # Campos específicos de Funcionamento
    ALVARA: ["ALVARÁ", "ALVARA", "TIPO ALVARÁ", "TIPO ALVARA"]
    MUNICIPIO: ["MUNICÍPIO", "MUNICIPIO", "CIDADE"]

  processos_bombeiros:
    ID: ["ID"]
    EMPRESA: ["EMPRESA", "RAZÃO SOCIAL", "RAZAO SOCIAL"]
    CNPJ: ["CNPJ"]
    PROTOCOLO: ["PROTOCOLO", "Nº PROTOCOLO"]
    DATA_SOLICITACAO: ["DATA SOLICITAÇÃO", "DATA SOLICITACAO"]
    SITUACAO: ["SITUAÇÃO", "SITUACAO", "STATUS"]
    PRAZO: ["PRAZO"]
    OBS: ["OBS", "OBSERVAÇÃO"]
    # Campos específicos de Bombeiros
    TPI: ["TPI", "TAXA POTENCIAL INCÊNDIO", "TAXA POTENCIAL INCENDIO"]

  processos_uso_solo:
    ID: ["ID"]
    EMPRESA: ["EMPRESA", "RAZÃO SOCIAL"]
    CNPJ: ["CNPJ"]
    PROTOCOLO: ["PROTOCOLO"]
    DATA_SOLICITACAO: ["DATA SOLICITAÇÃO", "DATA SOLICITACAO"]
    SITUACAO: ["SITUAÇÃO", "SITUACAO"]
    PRAZO: ["PRAZO"]
    OBS: ["OBS"]
    # Campos específicos de Uso do Solo
    INSCRICAO_IMOBILIARIA: ["INSCRIÇÃO IMOBILIÁRIA", "INSCRICAO IMOBILIARIA", "INSC IMOBILIÁRIA", "INSC IMOBILIARIA"]

  processos_sanitario:
    ID: ["ID"]
    EMPRESA: ["EMPRESA", "RAZÃO SOCIAL"]
    CNPJ: ["CNPJ"]
    PROTOCOLO: ["PROTOCOLO"]
    DATA_SOLICITACAO: ["DATA SOLICITAÇÃO", "DATA SOLICITACAO"]
    SITUACAO: ["SITUAÇÃO", "SITUACAO"]
    PRAZO: ["PRAZO"]
    OBS: ["OBS"]
    # Campos específicos de Sanitário
    SERVICO: ["SERVIÇO", "SERVICO", "TIPO SERVIÇO", "TIPO SERVICO"]
    TAXA: ["TAXA", "SITUAÇÃO TAXA", "SITUACAO TAXA"]
    NOTIFICACAO: ["NOTIFICAÇÃO", "NOTIFICACAO", "STATUS NOTIFICAÇÃO", "STATUS NOTIFICACAO"]
    DATA_VAL: ["DATA VAL", "DATA VALIDADE", "VALIDADE"]

  processos_ambiental:
    ID: ["ID"]
    EMPRESA: ["EMPRESA", "RAZÃO SOCIAL"]
    CNPJ: ["CNPJ"]
    PROTOCOLO: ["PROTOCOLO"]
    DATA_SOLICITACAO: ["DATA SOLICITAÇÃO", "DATA SOLICITACAO"]
    SITUACAO: ["SITUAÇÃO", "SITUACAO"]
    PRAZO: ["PRAZO"]
    OBS: ["OBS"]
    # Ambiental não tem campos específicos adicionais segundo o dicionário

  uteis_contatos:
    CONTATO: ["CONTATO"]
    MUNICIPIO: ["MUNICÍPIO"]
    TELEFONE: ["TELEFONE"]
    WHATSAPP: ["WHATSAPP"]
    E_MAIL: ["E-MAIL"]
    CATEGORIA: ["CATEGORIA"]
  
  uteis_modelos:
    MODELO: ["MODELO"]
    DESCRICAO: ["DESCRIÇÃO"]
    UTILIZACAO: ["UTILIZAÇÃO"]
